"""Shared constants."""

SCRIPT_NAME = "ipvsman.py"
SYSLOG_IDENT = "ipvsman"

DEFAULT_TICK_INTERVAL = 5.0
DEFAULT_RELOAD_INTERVAL = 30.0
DEFAULT_STATS_INTERVAL = 15.0
DEFAULT_CHECK_WORKERS = 16
DEFAULT_SHUTDOWN_TIMEOUT = 10.0
DEFAULT_COLD_START_SEC = 30.0
DEFAULT_STALE_GRACE_SEC = 30.0

DEFAULT_LOCK_FILE = "/run/ipvsman/ipvsman.lock"
DEFAULT_CONFIG_DIR = "/usr/local/etc/ipvsman"

DEFAULT_API_HOST = "127.0.0.1"
DEFAULT_API_PORT = 9111
DEFAULT_API_MAX_BODY_BYTES = 1024 * 1024
DEFAULT_API_TOKEN_ENV = "IPVSMAN_API_TOKEN"
DEFAULT_API_RATE_LIMIT_PER_MINUTE = 300

DEFAULT_PROM_HOST = "localhost"
DEFAULT_PROM_PORT = 9110

MAX_CONFIG_FILE_BYTES = 1024 * 1024
MAX_CONFIG_FILES = 10000

HEALTH_UNKNOWN = 0
HEALTH_HEALTHY = 1
HEALTH_UNHEALTHY = 2

# Bits merged from --list-services / --list-frontends / --list-backends / --list-healthchecks
LIST_MASK_SERVICES = 1
LIST_MASK_FRONTENDS = 2
LIST_MASK_BACKENDS = 4
LIST_MASK_HEALTHCHECKS = 8
